name: dictapro
description: DictaPro - voice recorder with AI transcription
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  record: 5.1.0
  just_audio: 0.9.42
  hive: 2.2.3
  hive_flutter: 1.1.0
  path_provider: 2.1.5
  permission_handler: 10.4.5
  intl: 0.20.2
  vosk_flutter: 0.3.48
  share_plus: 10.0.0
  file_picker: 6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  hive_generator: 2.0.1
  build_runner: 2.4.13
  flutter_launcher_icons: 0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/vosk-model-small-ru-0.22.zip